import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync } from 'node:fs';
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		esbuildSvelte({
			preprocess: sveltePreprocess(),
			compilerOptions: {
				css: 'injected'
			}
		})
	],
});

// Copy sql.js WASM binary alongside main.js (idempotent)
copyFileSync('node_modules/sql.js/dist/sql-wasm.wasm', 'sql-wasm.wasm');

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
